openapi: 3.0.0
info:
  contact:
    url: https://help.yahoo.com/kb/finance-for-web
  description: Yahoo Finance API specification
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.verizonmedia.com/policies/us/en/verizonmedia/terms/otos/index.html
  title: Yahoo Finance
  version: 1.0.4
servers:
- url: https://query1.finance.yahoo.com
tags:
- name: chart
- name: quote
- name: spark
paths:
  /v8/finance/chart/{symbol}:
    get:
      operationId: GetChart
      parameters:
      - explode: false
        in: path
        name: symbol
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: region
        required: false
        schema:
          enum:
          - US
          type: string
        style: form
      - explode: true
        in: query
        name: includePrePost
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - explode: true
        in: query
        name: lang
        required: false
        schema:
          enum:
          - en-US
          type: string
        style: form
      - explode: true
        in: query
        name: interval
        required: true
        schema:
          $ref: '#/components/schemas/Interval'
        style: form
      - explode: true
        in: query
        name: useYfid
        required: false
        schema:
          default: true
          type: boolean
        style: form
      - explode: true
        in: query
        name: period1
        required: true
        schema:
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: period2
        required: true
        schema:
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: corsDomain
        required: false
        schema:
          enum:
          - finance.yahoo.com
          type: string
        style: form
      - explode: true
        in: query
        name: .tsrc
        required: false
        schema:
          enum:
          - finance
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChartResponse'
          description: OK
      tags:
      - chart
  /v7/finance/quote:
    get:
      description: Returns quotes for the specified symbols
      operationId: GetQuote
      parameters:
      - explode: true
        in: query
        name: formatted
        required: false
        schema:
          default: true
          type: boolean
        style: form
      - explode: true
        in: query
        name: region
        required: false
        schema:
          enum:
          - US
          type: string
        style: form
      - explode: true
        in: query
        name: lang
        required: false
        schema:
          enum:
          - en-US
          type: string
        style: form
      - explode: true
        in: query
        name: includePrePost
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - explode: true
        in: query
        name: fields
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: corsDomain
        required: false
        schema:
          enum:
          - finance.yahoo.com
          type: string
        style: form
      - explode: true
        in: query
        name: symbols
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteResponse'
          description: OK
      summary: Returns quotes for the specified symbols
      tags:
      - quote
  /v7/finance/spark:
    get:
      operationId: Spark
      parameters:
      - explode: true
        in: query
        name: interval
        required: true
        schema:
          $ref: '#/components/schemas/Interval'
        style: form
      - explode: true
        in: query
        name: range
        required: true
        schema:
          $ref: '#/components/schemas/Range'
        style: form
      - explode: true
        in: query
        name: lang
        required: false
        schema:
          enum:
          - en-US
          type: string
        style: form
      - explode: true
        in: query
        name: includePrePost
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - explode: true
        in: query
        name: includeTimestamps
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - explode: true
        in: query
        name: indicators
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: corsDomain
        required: false
        schema:
          enum:
          - finance.yahoo.com
          type: string
        style: form
      - explode: true
        in: query
        name: symbols
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteResponse'
          description: OK
      tags:
      - spark
components:
  schemas:
    Interval:
      enum:
      - 1m
      - 5m
      - 15m
      - 30m
      - 1h
      - 6h
      - 1d
      type: string
    Range:
      enum:
      - 1d
      - 5d
      - 1mo
      - 3mo
      - 6mo
      - 1y
      - 2y
      - 5y
      - 10y
      - ytd
      - max
      type: string
    QuoteResult:
      example:
        fullExchangeName: SNP
        symbol: ^GSPC
        fiftyTwoWeekLowChangePercent:
          raw: 0.5613753
          fmt: 56.14%
        gmtOffSetMilliseconds: -14400000
        regularMarketOpen:
          raw: 3992.78
          fmt: "3992.78"
        language: en-US
        regularMarketTime:
          raw: 1617311722
          fmt: 5:15PM EDT
        regularMarketChangePercent:
          raw: 1.1825202
          fmt: 1.18%
        quoteType: INDEX
        uuid: 8ffd55d1-3d1d-3733-a480-56768bc708e6
        regularMarketDayRange:
          raw: 3992.78 - 4020.63
          fmt: 3992.78 - 4020.63
        fiftyTwoWeekLowChange:
          raw: 1445.3
          fmt: "1445.3"
        fiftyTwoWeekHighChangePercent:
          raw: -0.00018896682
          fmt: -0.02%
        regularMarketDayHigh:
          raw: 4020.63
          fmt: "4020.63"
        tradeable: true
        currency: USD
        fiftyTwoWeekHigh:
          raw: 4020.63
          fmt: "4020.63"
        regularMarketPreviousClose:
          raw: 3972.89
          fmt: "3972.89"
        exchangeTimezoneName: America/New_York
        fiftyTwoWeekHighChange:
          raw: -0.7597656
          fmt: -0.76
        regularMarketChange:
          raw: 46.980225
          fmt: "46.98"
        fiftyTwoWeekRange:
          raw: 2574.57 - 4020.63
          fmt: 2574.57 - 4020.63
        exchangeDataDelayedBy: 0
        firstTradeDateMilliseconds: 0
        exchangeTimezoneShortName: EDT
        marketState: CLOSED
        fiftyTwoWeekLow:
          raw: 2574.57
          fmt: "2574.57"
        regularMarketPrice:
          raw: 4019.87
          fmt: "4019.87"
        market: us_market
        regularMarketVolume:
          raw: 2165457735
          longFmt: "2165457735"
          fmt: 2.165B
        quoteSourceName: Delayed Quote
        messageBoardId: finmb_INDEXGSPC
        priceHint: 2
        exchange: SNP
        sourceInterval: 15
        regularMarketDayLow:
          raw: 3992.78
          fmt: "3992.78"
        region: US
        shortName: S&P 500
        triggerable: true
      properties:
        fullExchangeName:
          example: SNP
          type: string
        symbol:
          example: ^GSPC
          type: string
        fiftyTwoWeekLowChangePercent:
          $ref: '#/components/schemas/QuoteResult_fiftyTwoWeekLowChangePercent'
        gmtOffSetMilliseconds:
          example: -14400000
          format: int32
          type: integer
        regularMarketOpen:
          $ref: '#/components/schemas/QuoteResult_regularMarketOpen'
        language:
          example: en-US
          type: string
        regularMarketTime:
          $ref: '#/components/schemas/QuoteResult_regularMarketTime'
        regularMarketChangePercent:
          $ref: '#/components/schemas/QuoteResult_regularMarketChangePercent'
        quoteType:
          example: INDEX
          type: string
        uuid:
          example: 8ffd55d1-3d1d-3733-a480-56768bc708e6
          type: string
        regularMarketDayRange:
          $ref: '#/components/schemas/QuoteResult_regularMarketDayRange'
        fiftyTwoWeekLowChange:
          $ref: '#/components/schemas/QuoteResult_fiftyTwoWeekLowChange'
        fiftyTwoWeekHighChangePercent:
          $ref: '#/components/schemas/QuoteResult_fiftyTwoWeekHighChangePercent'
        regularMarketDayHigh:
          $ref: '#/components/schemas/QuoteResult_regularMarketDayHigh'
        tradeable:
          type: boolean
        currency:
          example: USD
          type: string
        fiftyTwoWeekHigh:
          $ref: '#/components/schemas/QuoteResult_regularMarketDayHigh'
        regularMarketPreviousClose:
          $ref: '#/components/schemas/QuoteResult_regularMarketPreviousClose'
        exchangeTimezoneName:
          example: America/New_York
          type: string
        fiftyTwoWeekHighChange:
          $ref: '#/components/schemas/QuoteResult_fiftyTwoWeekHighChange'
        regularMarketChange:
          $ref: '#/components/schemas/QuoteResult_regularMarketChange'
        fiftyTwoWeekRange:
          $ref: '#/components/schemas/QuoteResult_fiftyTwoWeekRange'
        exchangeDataDelayedBy:
          example: 0
          format: int32
          type: integer
        firstTradeDateMilliseconds:
          format: int64
          type: integer
        exchangeTimezoneShortName:
          example: EDT
          type: string
        marketState:
          example: CLOSED
          type: string
        fiftyTwoWeekLow:
          $ref: '#/components/schemas/QuoteResult_fiftyTwoWeekLow'
        regularMarketPrice:
          $ref: '#/components/schemas/QuoteResult_regularMarketPrice'
        market:
          example: us_market
          type: string
        regularMarketVolume:
          $ref: '#/components/schemas/QuoteResult_regularMarketVolume'
        quoteSourceName:
          example: Delayed Quote
          type: string
        messageBoardId:
          example: finmb_INDEXGSPC
          type: string
        priceHint:
          example: 2
          format: int32
          type: integer
        exchange:
          example: SNP
          type: string
        sourceInterval:
          example: 15
          format: int32
          type: integer
        regularMarketDayLow:
          $ref: '#/components/schemas/QuoteResult_regularMarketOpen'
        region:
          example: US
          type: string
        shortName:
          example: S&P 500
          type: string
        triggerable:
          type: boolean
      type: object
    QuoteResponse:
      example:
        result:
        - fullExchangeName: SNP
          symbol: ^GSPC
          fiftyTwoWeekLowChangePercent:
            raw: 0.5613753
            fmt: 56.14%
          gmtOffSetMilliseconds: -14400000
          regularMarketOpen:
            raw: 3992.78
            fmt: "3992.78"
          language: en-US
          regularMarketTime:
            raw: 1617311722
            fmt: 5:15PM EDT
          regularMarketChangePercent:
            raw: 1.1825202
            fmt: 1.18%
          quoteType: INDEX
          uuid: 8ffd55d1-3d1d-3733-a480-56768bc708e6
          regularMarketDayRange:
            raw: 3992.78 - 4020.63
            fmt: 3992.78 - 4020.63
          fiftyTwoWeekLowChange:
            raw: 1445.3
            fmt: "1445.3"
          fiftyTwoWeekHighChangePercent:
            raw: -0.00018896682
            fmt: -0.02%
          regularMarketDayHigh:
            raw: 4020.63
            fmt: "4020.63"
          tradeable: true
          currency: USD
          fiftyTwoWeekHigh:
            raw: 4020.63
            fmt: "4020.63"
          regularMarketPreviousClose:
            raw: 3972.89
            fmt: "3972.89"
          exchangeTimezoneName: America/New_York
          fiftyTwoWeekHighChange:
            raw: -0.7597656
            fmt: -0.76
          regularMarketChange:
            raw: 46.980225
            fmt: "46.98"
          fiftyTwoWeekRange:
            raw: 2574.57 - 4020.63
            fmt: 2574.57 - 4020.63
          exchangeDataDelayedBy: 0
          firstTradeDateMilliseconds: 0
          exchangeTimezoneShortName: EDT
          marketState: CLOSED
          fiftyTwoWeekLow:
            raw: 2574.57
            fmt: "2574.57"
          regularMarketPrice:
            raw: 4019.87
            fmt: "4019.87"
          market: us_market
          regularMarketVolume:
            raw: 2165457735
            longFmt: "2165457735"
            fmt: 2.165B
          quoteSourceName: Delayed Quote
          messageBoardId: finmb_INDEXGSPC
          priceHint: 2
          exchange: SNP
          sourceInterval: 15
          regularMarketDayLow:
            raw: 3992.78
            fmt: "3992.78"
          region: US
          shortName: S&P 500
          triggerable: true
        - fullExchangeName: SNP
          symbol: ^GSPC
          fiftyTwoWeekLowChangePercent:
            raw: 0.5613753
            fmt: 56.14%
          gmtOffSetMilliseconds: -14400000
          regularMarketOpen:
            raw: 3992.78
            fmt: "3992.78"
          language: en-US
          regularMarketTime:
            raw: 1617311722
            fmt: 5:15PM EDT
          regularMarketChangePercent:
            raw: 1.1825202
            fmt: 1.18%
          quoteType: INDEX
          uuid: 8ffd55d1-3d1d-3733-a480-56768bc708e6
          regularMarketDayRange:
            raw: 3992.78 - 4020.63
            fmt: 3992.78 - 4020.63
          fiftyTwoWeekLowChange:
            raw: 1445.3
            fmt: "1445.3"
          fiftyTwoWeekHighChangePercent:
            raw: -0.00018896682
            fmt: -0.02%
          regularMarketDayHigh:
            raw: 4020.63
            fmt: "4020.63"
          tradeable: true
          currency: USD
          fiftyTwoWeekHigh:
            raw: 4020.63
            fmt: "4020.63"
          regularMarketPreviousClose:
            raw: 3972.89
            fmt: "3972.89"
          exchangeTimezoneName: America/New_York
          fiftyTwoWeekHighChange:
            raw: -0.7597656
            fmt: -0.76
          regularMarketChange:
            raw: 46.980225
            fmt: "46.98"
          fiftyTwoWeekRange:
            raw: 2574.57 - 4020.63
            fmt: 2574.57 - 4020.63
          exchangeDataDelayedBy: 0
          firstTradeDateMilliseconds: 0
          exchangeTimezoneShortName: EDT
          marketState: CLOSED
          fiftyTwoWeekLow:
            raw: 2574.57
            fmt: "2574.57"
          regularMarketPrice:
            raw: 4019.87
            fmt: "4019.87"
          market: us_market
          regularMarketVolume:
            raw: 2165457735
            longFmt: "2165457735"
            fmt: 2.165B
          quoteSourceName: Delayed Quote
          messageBoardId: finmb_INDEXGSPC
          priceHint: 2
          exchange: SNP
          sourceInterval: 15
          regularMarketDayLow:
            raw: 3992.78
            fmt: "3992.78"
          region: US
          shortName: S&P 500
          triggerable: true
        error: error
      properties:
        result:
          items:
            $ref: '#/components/schemas/QuoteResult'
          type: array
        error:
          format: nullable
          type: string
      type: object
    ChartResponse:
      example:
        chart:
          result:
          - meta:
              exchangeTimezoneName: Europe/London
              symbol: EURUSD=X
              instrumentType: CURRENCY
              firstTradeDate: 1070236800
              timezone: BST
              scale: 4
              range: 1d
              regularMarketTime: 1617398979
              dataGranularity: 2m
              validRanges:
              - 1d
              - 1d
              regularMarketPrice: 1.1769
              tradingPeriods:
              - - '{}'
                - '{}'
              - - '{}'
                - '{}'
              previousClose: 1.178
              gmtoffset: 3600
              chartPreviousClose: 1.178
              priceHint: 4
              currency: USD
              exchangeName: CCY
              currentTradingPeriod:
                pre:
                  gmtoffset: 3600
                  timezone: BST
                  start: 1617318000
                  end: 1617318000
                post:
                  gmtoffset: 3600
                  timezone: BST
                  start: 1617404340
                  end: 1617404340
                regular:
                  gmtoffset: 3600
                  timezone: BST
                  start: 1617318000
                  end: 1617404340
            indicators:
              quote:
              - volume:
                - 0
                - 0
                high:
                - 1.1784114837646484
                - 1.1784114837646484
                low:
                - 1.1782727241516113
                - 1.1782727241516113
                close:
                - 1.1782727241516113
                - 1.1782727241516113
                open:
                - 1.1784114837646484
                - 1.1784114837646484
              - volume:
                - 0
                - 0
                high:
                - 1.1784114837646484
                - 1.1784114837646484
                low:
                - 1.1782727241516113
                - 1.1782727241516113
                close:
                - 1.1782727241516113
                - 1.1782727241516113
                open:
                - 1.1784114837646484
                - 1.1784114837646484
            timestamp:
            - 1617318000
            - 1617318000
          - meta:
              exchangeTimezoneName: Europe/London
              symbol: EURUSD=X
              instrumentType: CURRENCY
              firstTradeDate: 1070236800
              timezone: BST
              scale: 4
              range: 1d
              regularMarketTime: 1617398979
              dataGranularity: 2m
              validRanges:
              - 1d
              - 1d
              regularMarketPrice: 1.1769
              tradingPeriods:
              - - '{}'
                - '{}'
              - - '{}'
                - '{}'
              previousClose: 1.178
              gmtoffset: 3600
              chartPreviousClose: 1.178
              priceHint: 4
              currency: USD
              exchangeName: CCY
              currentTradingPeriod:
                pre:
                  gmtoffset: 3600
                  timezone: BST
                  start: 1617318000
                  end: 1617318000
                post:
                  gmtoffset: 3600
                  timezone: BST
                  start: 1617404340
                  end: 1617404340
                regular:
                  gmtoffset: 3600
                  timezone: BST
                  start: 1617318000
                  end: 1617404340
            indicators:
              quote:
              - volume:
                - 0
                - 0
                high:
                - 1.1784114837646484
                - 1.1784114837646484
                low:
                - 1.1782727241516113
                - 1.1782727241516113
                close:
                - 1.1782727241516113
                - 1.1782727241516113
                open:
                - 1.1784114837646484
                - 1.1784114837646484
              - volume:
                - 0
                - 0
                high:
                - 1.1784114837646484
                - 1.1784114837646484
                low:
                - 1.1782727241516113
                - 1.1782727241516113
                close:
                - 1.1782727241516113
                - 1.1782727241516113
                open:
                - 1.1784114837646484
                - 1.1784114837646484
            timestamp:
            - 1617318000
            - 1617318000
          error: error
      properties:
        chart:
          $ref: '#/components/schemas/ChartResponse_chart'
      type: object
    SparkResponse:
      properties:
        spark:
          $ref: '#/components/schemas/SparkResponse_spark'
      type: object
    QuoteResult_fiftyTwoWeekLowChangePercent:
      example:
        raw: 0.5613753
        fmt: 56.14%
      properties:
        raw:
          example: 0.5613753
          type: number
        fmt:
          example: 56.14%
          type: string
      type: object
    QuoteResult_regularMarketOpen:
      example:
        raw: 3992.78
        fmt: "3992.78"
      properties:
        raw:
          example: 3992.78
          type: number
        fmt:
          example: "3992.78"
          type: string
      type: object
    QuoteResult_regularMarketTime:
      example:
        raw: 1617311722
        fmt: 5:15PM EDT
      properties:
        raw:
          example: 1617311722
          format: int32
          type: integer
        fmt:
          example: 5:15PM EDT
          type: string
      type: object
    QuoteResult_regularMarketChangePercent:
      example:
        raw: 1.1825202
        fmt: 1.18%
      properties:
        raw:
          example: 1.1825202
          type: number
        fmt:
          example: 1.18%
          type: string
      type: object
    QuoteResult_regularMarketDayRange:
      example:
        raw: 3992.78 - 4020.63
        fmt: 3992.78 - 4020.63
      properties:
        raw:
          example: 3992.78 - 4020.63
          type: string
        fmt:
          example: 3992.78 - 4020.63
          type: string
      type: object
    QuoteResult_fiftyTwoWeekLowChange:
      example:
        raw: 1445.3
        fmt: "1445.3"
      properties:
        raw:
          example: 1445.3
          type: number
        fmt:
          example: "1445.3"
          type: string
      type: object
    QuoteResult_fiftyTwoWeekHighChangePercent:
      example:
        raw: -0.00018896682
        fmt: -0.02%
      properties:
        raw:
          example: -0.00018896682
          type: number
        fmt:
          example: -0.02%
          type: string
      type: object
    QuoteResult_regularMarketDayHigh:
      example:
        raw: 4020.63
        fmt: "4020.63"
      properties:
        raw:
          example: 4020.63
          type: number
        fmt:
          example: "4020.63"
          type: string
      type: object
    QuoteResult_regularMarketPreviousClose:
      example:
        raw: 3972.89
        fmt: "3972.89"
      properties:
        raw:
          example: 3972.89
          type: number
        fmt:
          example: "3972.89"
          type: string
      type: object
    QuoteResult_fiftyTwoWeekHighChange:
      example:
        raw: -0.7597656
        fmt: -0.76
      properties:
        raw:
          example: -0.7597656
          type: number
        fmt:
          example: -0.76
          type: string
      type: object
    QuoteResult_regularMarketChange:
      example:
        raw: 46.980225
        fmt: "46.98"
      properties:
        raw:
          example: 46.980225
          type: number
        fmt:
          example: "46.98"
          type: string
      type: object
    QuoteResult_fiftyTwoWeekRange:
      example:
        raw: 2574.57 - 4020.63
        fmt: 2574.57 - 4020.63
      properties:
        raw:
          example: 2574.57 - 4020.63
          type: string
        fmt:
          example: 2574.57 - 4020.63
          type: string
      type: object
    QuoteResult_fiftyTwoWeekLow:
      example:
        raw: 2574.57
        fmt: "2574.57"
      properties:
        raw:
          example: 2574.57
          type: number
        fmt:
          example: "2574.57"
          type: string
      type: object
    QuoteResult_regularMarketPrice:
      example:
        raw: 4019.87
        fmt: "4019.87"
      properties:
        raw:
          example: 4019.87
          type: number
        fmt:
          example: "4019.87"
          type: string
      type: object
    QuoteResult_regularMarketVolume:
      example:
        raw: 2165457735
        longFmt: "2165457735"
        fmt: 2.165B
      properties:
        raw:
          example: 2165457735
          format: int64
          type: integer
        fmt:
          example: 2.165B
          type: string
        longFmt:
          example: "2165457735"
          type: string
      type: object
    ChartResponse_chart_meta_currentTradingPeriod_pre:
      example:
        gmtoffset: 3600
        timezone: BST
        start: 1617318000
        end: 1617318000
      properties:
        timezone:
          example: BST
          type: string
        start:
          example: 1617318000
          format: int32
          type: integer
        end:
          example: 1617318000
          format: int32
          type: integer
        gmtoffset:
          example: 3600
          format: int32
          type: integer
      type: object
    ChartResponse_chart_meta_currentTradingPeriod_regular:
      example:
        gmtoffset: 3600
        timezone: BST
        start: 1617318000
        end: 1617404340
      properties:
        timezone:
          example: BST
          type: string
        start:
          example: 1617318000
          format: int32
          type: integer
        end:
          example: 1617404340
          format: int32
          type: integer
        gmtoffset:
          example: 3600
          format: int32
          type: integer
      type: object
    ChartResponse_chart_meta_currentTradingPeriod_post:
      example:
        gmtoffset: 3600
        timezone: BST
        start: 1617404340
        end: 1617404340
      properties:
        timezone:
          example: BST
          type: string
        start:
          example: 1617404340
          format: int32
          type: integer
        end:
          example: 1617404340
          format: int32
          type: integer
        gmtoffset:
          example: 3600
          format: int32
          type: integer
      type: object
    ChartResponse_chart_meta_currentTradingPeriod:
      example:
        pre:
          gmtoffset: 3600
          timezone: BST
          start: 1617318000
          end: 1617318000
        post:
          gmtoffset: 3600
          timezone: BST
          start: 1617404340
          end: 1617404340
        regular:
          gmtoffset: 3600
          timezone: BST
          start: 1617318000
          end: 1617404340
      properties:
        pre:
          $ref: '#/components/schemas/ChartResponse_chart_meta_currentTradingPeriod_pre'
        regular:
          $ref: '#/components/schemas/ChartResponse_chart_meta_currentTradingPeriod_regular'
        post:
          $ref: '#/components/schemas/ChartResponse_chart_meta_currentTradingPeriod_post'
      type: object
    ChartResponse_chart_meta:
      example:
        exchangeTimezoneName: Europe/London
        symbol: EURUSD=X
        instrumentType: CURRENCY
        firstTradeDate: 1070236800
        timezone: BST
        scale: 4
        range: 1d
        regularMarketTime: 1617398979
        dataGranularity: 2m
        validRanges:
        - 1d
        - 1d
        regularMarketPrice: 1.1769
        tradingPeriods:
        - - '{}'
          - '{}'
        - - '{}'
          - '{}'
        previousClose: 1.178
        gmtoffset: 3600
        chartPreviousClose: 1.178
        priceHint: 4
        currency: USD
        exchangeName: CCY
        currentTradingPeriod:
          pre:
            gmtoffset: 3600
            timezone: BST
            start: 1617318000
            end: 1617318000
          post:
            gmtoffset: 3600
            timezone: BST
            start: 1617404340
            end: 1617404340
          regular:
            gmtoffset: 3600
            timezone: BST
            start: 1617318000
            end: 1617404340
      properties:
        currency:
          example: USD
          type: string
        symbol:
          example: EURUSD=X
          type: string
        exchangeName:
          example: CCY
          type: string
        instrumentType:
          example: CURRENCY
          type: string
        firstTradeDate:
          example: 1070236800
          format: int32
          type: integer
        regularMarketTime:
          example: 1617398979
          format: int32
          type: integer
        gmtoffset:
          example: 3600
          format: int32
          type: integer
        timezone:
          example: BST
          type: string
        exchangeTimezoneName:
          example: Europe/London
          type: string
        regularMarketPrice:
          example: 1.1769
          type: number
        chartPreviousClose:
          example: 1.178
          type: number
        previousClose:
          example: 1.178
          type: number
        scale:
          example: 4
          format: int32
          type: integer
        priceHint:
          example: 4
          format: int32
          type: integer
        currentTradingPeriod:
          $ref: '#/components/schemas/ChartResponse_chart_meta_currentTradingPeriod'
        tradingPeriods:
          items:
            items:
              properties:
                timezone:
                  example: BST
                  type: string
                start:
                  example: 1617318000
                  format: int32
                  type: integer
                end:
                  example: 1617404340
                  format: int32
                  type: integer
                gmtoffset:
                  example: 3600
                  format: int32
                  type: integer
              type: object
            type: array
          type: array
        dataGranularity:
          example: 2m
          type: string
        range:
          example: 1d
          type: string
        validRanges:
          items:
            example: 1d
            type: string
          type: array
      type: object
    ChartResponse_chart_indicators_quote:
      example:
        volume:
        - 0
        - 0
        high:
        - 1.1784114837646484
        - 1.1784114837646484
        low:
        - 1.1782727241516113
        - 1.1782727241516113
        close:
        - 1.1782727241516113
        - 1.1782727241516113
        open:
        - 1.1784114837646484
        - 1.1784114837646484
      properties:
        high:
          items:
            example: 1.1784114837646484
            type: number
          type: array
        close:
          items:
            example: 1.1782727241516113
            type: number
          type: array
        volume:
          items:
            example: 0
            format: int32
            type: integer
          type: array
        low:
          items:
            example: 1.1782727241516113
            type: number
          type: array
        open:
          items:
            example: 1.1784114837646484
            type: number
          type: array
      type: object
    ChartResponse_chart_indicators:
      example:
        quote:
        - volume:
          - 0
          - 0
          high:
          - 1.1784114837646484
          - 1.1784114837646484
          low:
          - 1.1782727241516113
          - 1.1782727241516113
          close:
          - 1.1782727241516113
          - 1.1782727241516113
          open:
          - 1.1784114837646484
          - 1.1784114837646484
        - volume:
          - 0
          - 0
          high:
          - 1.1784114837646484
          - 1.1784114837646484
          low:
          - 1.1782727241516113
          - 1.1782727241516113
          close:
          - 1.1782727241516113
          - 1.1782727241516113
          open:
          - 1.1784114837646484
          - 1.1784114837646484
      properties:
        quote:
          items:
            $ref: '#/components/schemas/ChartResponse_chart_indicators_quote'
          type: array
      type: object
    ChartResponse_chart_result:
      example:
        meta:
          exchangeTimezoneName: Europe/London
          symbol: EURUSD=X
          instrumentType: CURRENCY
          firstTradeDate: 1070236800
          timezone: BST
          scale: 4
          range: 1d
          regularMarketTime: 1617398979
          dataGranularity: 2m
          validRanges:
          - 1d
          - 1d
          regularMarketPrice: 1.1769
          tradingPeriods:
          - - '{}'
            - '{}'
          - - '{}'
            - '{}'
          previousClose: 1.178
          gmtoffset: 3600
          chartPreviousClose: 1.178
          priceHint: 4
          currency: USD
          exchangeName: CCY
          currentTradingPeriod:
            pre:
              gmtoffset: 3600
              timezone: BST
              start: 1617318000
              end: 1617318000
            post:
              gmtoffset: 3600
              timezone: BST
              start: 1617404340
              end: 1617404340
            regular:
              gmtoffset: 3600
              timezone: BST
              start: 1617318000
              end: 1617404340
        indicators:
          quote:
          - volume:
            - 0
            - 0
            high:
            - 1.1784114837646484
            - 1.1784114837646484
            low:
            - 1.1782727241516113
            - 1.1782727241516113
            close:
            - 1.1782727241516113
            - 1.1782727241516113
            open:
            - 1.1784114837646484
            - 1.1784114837646484
          - volume:
            - 0
            - 0
            high:
            - 1.1784114837646484
            - 1.1784114837646484
            low:
            - 1.1782727241516113
            - 1.1782727241516113
            close:
            - 1.1782727241516113
            - 1.1782727241516113
            open:
            - 1.1784114837646484
            - 1.1784114837646484
        timestamp:
        - 1617318000
        - 1617318000
      properties:
        meta:
          $ref: '#/components/schemas/ChartResponse_chart_meta'
        timestamp:
          items:
            example: 1617318000
            format: int32
            type: integer
          type: array
        indicators:
          $ref: '#/components/schemas/ChartResponse_chart_indicators'
      type: object
    ChartResponse_chart:
      example:
        result:
        - meta:
            exchangeTimezoneName: Europe/London
            symbol: EURUSD=X
            instrumentType: CURRENCY
            firstTradeDate: 1070236800
            timezone: BST
            scale: 4
            range: 1d
            regularMarketTime: 1617398979
            dataGranularity: 2m
            validRanges:
            - 1d
            - 1d
            regularMarketPrice: 1.1769
            tradingPeriods:
            - - '{}'
              - '{}'
            - - '{}'
              - '{}'
            previousClose: 1.178
            gmtoffset: 3600
            chartPreviousClose: 1.178
            priceHint: 4
            currency: USD
            exchangeName: CCY
            currentTradingPeriod:
              pre:
                gmtoffset: 3600
                timezone: BST
                start: 1617318000
                end: 1617318000
              post:
                gmtoffset: 3600
                timezone: BST
                start: 1617404340
                end: 1617404340
              regular:
                gmtoffset: 3600
                timezone: BST
                start: 1617318000
                end: 1617404340
          indicators:
            quote:
            - volume:
              - 0
              - 0
              high:
              - 1.1784114837646484
              - 1.1784114837646484
              low:
              - 1.1782727241516113
              - 1.1782727241516113
              close:
              - 1.1782727241516113
              - 1.1782727241516113
              open:
              - 1.1784114837646484
              - 1.1784114837646484
            - volume:
              - 0
              - 0
              high:
              - 1.1784114837646484
              - 1.1784114837646484
              low:
              - 1.1782727241516113
              - 1.1782727241516113
              close:
              - 1.1782727241516113
              - 1.1782727241516113
              open:
              - 1.1784114837646484
              - 1.1784114837646484
          timestamp:
          - 1617318000
          - 1617318000
        - meta:
            exchangeTimezoneName: Europe/London
            symbol: EURUSD=X
            instrumentType: CURRENCY
            firstTradeDate: 1070236800
            timezone: BST
            scale: 4
            range: 1d
            regularMarketTime: 1617398979
            dataGranularity: 2m
            validRanges:
            - 1d
            - 1d
            regularMarketPrice: 1.1769
            tradingPeriods:
            - - '{}'
              - '{}'
            - - '{}'
              - '{}'
            previousClose: 1.178
            gmtoffset: 3600
            chartPreviousClose: 1.178
            priceHint: 4
            currency: USD
            exchangeName: CCY
            currentTradingPeriod:
              pre:
                gmtoffset: 3600
                timezone: BST
                start: 1617318000
                end: 1617318000
              post:
                gmtoffset: 3600
                timezone: BST
                start: 1617404340
                end: 1617404340
              regular:
                gmtoffset: 3600
                timezone: BST
                start: 1617318000
                end: 1617404340
          indicators:
            quote:
            - volume:
              - 0
              - 0
              high:
              - 1.1784114837646484
              - 1.1784114837646484
              low:
              - 1.1782727241516113
              - 1.1782727241516113
              close:
              - 1.1782727241516113
              - 1.1782727241516113
              open:
              - 1.1784114837646484
              - 1.1784114837646484
            - volume:
              - 0
              - 0
              high:
              - 1.1784114837646484
              - 1.1784114837646484
              low:
              - 1.1782727241516113
              - 1.1782727241516113
              close:
              - 1.1782727241516113
              - 1.1782727241516113
              open:
              - 1.1784114837646484
              - 1.1784114837646484
          timestamp:
          - 1617318000
          - 1617318000
        error: error
      properties:
        result:
          items:
            $ref: '#/components/schemas/ChartResponse_chart_result'
          type: array
        error:
          format: nullable
          type: string
      type: object
    SparkResponse_spark_meta_currentTradingPeriod_pre:
      properties:
        timezone:
          type: string
        end:
          format: int32
          type: integer
        start:
          format: int32
          type: integer
        gmtoffset:
          format: int32
          type: integer
      type: object
    SparkResponse_spark_meta_currentTradingPeriod:
      properties:
        pre:
          $ref: '#/components/schemas/SparkResponse_spark_meta_currentTradingPeriod_pre'
        regular:
          $ref: '#/components/schemas/SparkResponse_spark_meta_currentTradingPeriod_pre'
        post:
          $ref: '#/components/schemas/SparkResponse_spark_meta_currentTradingPeriod_pre'
      type: object
    SparkResponse_spark_meta:
      properties:
        currency:
          type: string
        symbol:
          type: string
        exchangeName:
          type: string
        instrumentType:
          type: string
        firstTradeDate:
          format: int32
          type: integer
        regularMarketTime:
          format: int32
          type: integer
        gmtoffset:
          format: int32
          type: integer
        timezone:
          type: string
        exchangeTimezoneName:
          type: string
        regularMarketPrice:
          type: number
        chartPreviousClose:
          type: number
        previousClose:
          type: number
        scale:
          format: int32
          type: integer
        priceHint:
          format: int32
          type: integer
        currentTradingPeriod:
          $ref: '#/components/schemas/SparkResponse_spark_meta_currentTradingPeriod'
        tradingPeriods:
          items:
            items:
              properties:
                timezone:
                  type: string
                end:
                  format: int32
                  type: integer
                start:
                  format: int32
                  type: integer
                gmtoffset:
                  format: int32
                  type: integer
              type: object
            type: array
          type: array
        dataGranularity:
          type: string
        range:
          type: string
        validRanges:
          items:
            type: string
          type: array
      type: object
    SparkResponse_spark_indicators_quote:
      properties:
        close:
          items:
            type: number
          type: array
      type: object
    SparkResponse_spark_indicators:
      properties:
        quote:
          items:
            $ref: '#/components/schemas/SparkResponse_spark_indicators_quote'
          type: array
      type: object
    SparkResponse_spark_response:
      properties:
        meta:
          $ref: '#/components/schemas/SparkResponse_spark_meta'
        timestamp:
          items:
            format: int32
            type: integer
          type: array
        indicators:
          $ref: '#/components/schemas/SparkResponse_spark_indicators'
      type: object
    SparkResponse_spark_result:
      properties:
        symbol:
          type: string
        response:
          items:
            $ref: '#/components/schemas/SparkResponse_spark_response'
          type: array
      type: object
    SparkResponse_spark:
      properties:
        result:
          items:
            $ref: '#/components/schemas/SparkResponse_spark_result'
          type: array
        error:
          format: nullable
          type: string
      type: object
